Add list group members API endpoint
chanzuckerberg/czgenepi pull request #1098
Opened 2022-05-17 23:20 UTC by lvreynoso

### Summary:
- **What:** This is a first iteration of a list group members API endpoint. Pulls information from the database for all users in the current user's group. Members sorted alphabetically.
- **Ticket:** [sc187629](https://app.shortcut.com/genepi/story/187629)
- **Env:** [https://listmembers-backend.dev.czgenepi.org/v2/groups/members](https://listmembers-backend.dev.czgenepi.org/v2/groups/members)

### Demos:
<img width="572" alt="Screen Shot 2022-05-17 at 16 17 57" src="https://user-images.githubusercontent.com/24234461/168927568-dc763a59-34d1-402b-a0e9-52e228030d9b.png">

### Notes:

### Checklist:
- [ ] I merged latest `<base branch>`
- [ ] I manually verified the change
- [ ] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

2022-05-18 17:38 UTC, jgadling commented on src/backend/aspen/api/schemas/usergroup.py
> +    group_admin: bool
Should we include name here too?

2022-05-18 17:40 UTC, jgadling commented on src/backend/aspen/api/views/groups.py
> +@router.get("/members", response_model=AllGroupsMembersResponse)
I think this route should be `/v2/groups/[group_id]/members`

2022-05-18 17:42 UTC, lvreynoso commented on src/backend/aspen/api/schemas/usergroup.py
> +    group_admin: bool
That's part of the `UserBaseResponse`.

2022-05-18 17:44 UTC, jgadling requested changes

2022-05-18 17:44 UTC, jgadling commented on src/backend/aspen/api/schemas/usergroup.py
> +    group: GroupResponse
Can we have the group members endpoint just return all group members, and include group details in a separate `/v2/groups/[group_id]` endpoint?

2022-05-19 00:00 UTC, jgadling approved these changes

2022-05-19 00:11 UTC, merged