gisaid/genbank file prep sequences
chanzuckerberg/czgenepi pull request #1301
Opened 2022-08-27 01:28 UTC by phoenixAja

### Summary:
- **What:** add prefix depending on public repository name
- **Ticket:** [sc209564](https://app.shortcut.com/genepi/story/209564)
- **Env:** `<rdev link>`

### Demos:

### Notes:

### Checklist:
- [x] I merged latest `trunk`
- [x] I manually verified the change
- [x] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

2022-08-30 19:14 UTC, jgadling requested changes

2022-08-30 19:14 UTC, jgadling commented on src/backend/aspen/api/views/tests/test_sequences.py
> +    assert file_contents.startswith(">SARS-CoV-2/human/")
Please update these tests to ensure that the full sample names are correct!

2022-08-30 19:14 UTC, jgadling commented on src/backend/aspen/api/utils/fasta_streamer.py
> +                        PublicRepository.name == self.public_repository_name,
Just a headsup that this repository name is *case sensitive* and if we don't find a matching public repository, this endpoint doesn't return an error -- it just doesn't add prefixes to our sample names.

2022-08-30 20:34 UTC, phoenixAja commented
thanks for updating the cli @jgadling

2022-08-31 17:49 UTC, lvreynoso approved these changes
lgtm.

2022-08-31 20:47 UTC, jgadling requested changes
the lstrip() is broken -- why aren't the tests catching it?

2022-08-31 22:30 UTC, phoenixAja commented
the lstrip was working for me, i updated the tests to more specifically test that the old prefixes were stripped appropriately though.

2022-08-31 22:55 UTC, jgadling approved these changes

2022-09-01 18:11 UTC, merged