Disallow spaces in privateId
chanzuckerberg/czgenepi pull request #1660
Opened 2023-06-13 17:13 UTC by ehoops-cz

### Summary:
- **What:** Disallow spaces because nextstrain tree builds don't use them in the way we expect.
- **Ticket:** no ticket, on-call

### Demos: Fix for both SC2 and MPOX.  With spaces we no longer allow the upload. Without spaces we allow the upload.
![Screenshot 2023-06-13 at 9 54 05 AM](https://github.com/chanzuckerberg/czgenepi/assets/109251328/fbd25dde-b0de-469f-8f43-72310519a188)
![Screenshot 2023-06-13 at 9 53 42 AM](https://github.com/chanzuckerberg/czgenepi/assets/109251328/d4d15b1a-7443-4775-8acf-2f402c5052ca)
![Screenshot 2023-06-13 at 9 52 14 AM](https://github.com/chanzuckerberg/czgenepi/assets/109251328/fa25180f-5e55-47e2-8867-8c5c2b45fde6)
![Screenshot 2023-06-13 at 9 51 49 AM](https://github.com/chanzuckerberg/czgenepi/assets/109251328/20ec0654-b9ca-4c10-ab88-80e141148d17)

### Notes:

### Checklist:
- [ ] I merged latest `<base branch>`
- [ ] I manually verified the change
- [ ] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

2023-06-13 17:15 UTC, lvreynoso approved these changes
lgtm

2023-06-13 17:31 UTC, phoenixAja commented on src/frontend/src/views/Upload/components/common/constants.ts
> +export const FORBIDDEN_NAME_CHARACTERS_REGEX = /[^a-zA-Z0-9._/-]/;
i'm confused, this regex seems to be capturing all the charachters we do want, should this be renamed to ALLOWED_NAME_CHARACTERS_REGEX lol

2023-06-13 17:31 UTC, phoenixAja approved these changes

2023-06-13 18:53 UTC, lvreynoso requested changes

2023-06-13 18:53 UTC, lvreynoso commented on src/backend/aspen/database/models/sample.py
> +            self.public_identifier = sub(FORBIDDEN_NAME_CHARACTERS_REGEX, "", raw_public_identifier)
I think the regex string should leave out the leading and trailing forward slashes for Python. Also I think we can dedupe the sub call.

2023-06-14 20:15 UTC, ehoops-cz commented on src/frontend/src/views/Upload/components/common/constants.ts
> +export const FORBIDDEN_NAME_CHARACTERS_REGEX = /[^a-zA-Z0-9._/-]/;
I believe the `^` makes it so this selects for any character not in the defined characters

2023-06-14 20:17 UTC, ehoops-cz commented on src/frontend/src/views/Upload/components/common/constants.ts
> +export const FORBIDDEN_NAME_CHARACTERS_REGEX = /[^a-zA-Z0-9._/-]/;
I updated the comment to remove space from the allowed characters.

2023-06-14 21:33 UTC, lvreynoso approved these changes
looks great!

2023-06-15 14:31 UTC, merged