Add tree name to backend API response and use name in frontend table
chanzuckerberg/czgenepi pull request #408
Opened 2021-05-12 21:30 UTC by lvreynoso

### Description

Adds a `name` field to the phylo tree API response. Updates frontend table to use name field for the tree name.

![Screenshot from 2021-05-12 14-29-51](https://user-images.githubusercontent.com/24234461/118046724-91263580-b32e-11eb-9b84-1913075d35fb.png)
![Screenshot from 2021-05-12 14-28-22](https://user-images.githubusercontent.com/24234461/118046729-93888f80-b32e-11eb-8fcc-2b4db4fcee08.png)

#### Issue
[ch137015](https://app.clubhouse.io/genepi/story/137015)
[ch137507](https://app.clubhouse.io/genepi/story/137507)

### Test plan

Write how your changes are tested, or give a convincing reason why they can't be tested automatically.

2021-05-12 22:33 UTC, tihuan approved these changes
FE LGTM 🚀 🔥 !!

2021-05-12 23:29 UTC, ttung commented
public/private is a distinction that will make no sense to the dphs. furthermore, because we rewrite the trees, it's even less relevant.  i would just drop the public part.

2021-05-12 23:29 UTC, ttung commented
New trees are not likely to fit this naming scheme, btw.

2021-05-12 23:35 UTC, ttung requested changes
see comments.

2021-05-13 16:44 UTC, lvreynoso commented
Changed naming scheme to remove Public/Private.

2021-05-13 20:47 UTC, merged