Ondemand Tree builds v2
chanzuckerberg/czgenepi pull request #640
Opened 2021-08-19 00:03 UTC by jgadling

### Description

Support for ondemand tree builds v2.
- Import gisaid metadata into our db nightly
- PhyloRun start API accepts and validates gisaid ID's
- Phylo run script writes aspen & gisaid ID's to include.txt 

#### Issue
[ch153615](https://app.clubhouse.io/genepi/story/153615)

### Test plan

Write how your changes are tested, or give a convincing reason why they can't be tested automatically.

2021-08-19 20:21 UTC, lvreynoso requested changes
Looks good, just a question about the `import_id` column. Since I also wrote this PR and paired on it, would love for @shanaxel42 to also take a look.

2021-08-19 20:21 UTC, lvreynoso commented on src/backend/database_migrations/versions/20210813_172344_add_gisaid_metadata_table.py
> +        sa.Column("import_id", sa.String(), nullable=False),
This `import_id` column was removed from the model, do we still need it in the migration?

2021-08-19 20:21 UTC, lvreynoso commented on src/backend/database_migrations/versions/20210818_233848_remove_import_id.py
> +    pass
We can remove this whole file if we remove the `import_id` column from the other migration.

2021-08-27 17:18 UTC, jgadling commented on src/backend/database_migrations/versions/20210813_172344_add_gisaid_metadata_table.py
> +        sa.Column("import_id", sa.String(), nullable=False),
It's generally best not to modify db migration scripts once they've been published. Anyone who runs the migration in an earlier form won't have future changes applied to their DB and thus wind up out of sync. There are tradeoffs to be made here - performance issues, the likelihood of other db's having already applied a migration, etc.

2021-08-27 18:33 UTC, danrlu commented on src/backend/aspen/app/views/phylo_runs.py
> +    gisaid_matches: Iterable[GisaidMetadata] = g.db_session.query(
How long does such a query usually take against 3 million Gisaid records? Just curious

2021-08-27 18:37 UTC, jgadling commented on src/backend/aspen/app/views/phylo_runs.py
> +    gisaid_matches: Iterable[GisaidMetadata] = g.db_session.query(
The strain names are indexed, so it's O(nlogn) ... but 3m rows isn't much, these queries are very fast.

2021-08-27 18:38 UTC, danrlu commented on src/backend/aspen/app/views/phylo_runs.py
> +    gisaid_matches: Iterable[GisaidMetadata] = g.db_session.query(
LOL "but 3m rows isn't much"

2021-08-27 18:38 UTC, danrlu commented
I don't understand everything but tree part looks good to me! Exciting!

2021-08-27 20:48 UTC, lvreynoso approved these changes

2021-08-27 21:34 UTC, merged