WIP chore: Use chanzuckerberg/github-actions/docker-build-push in Push Remote Dev action
chanzuckerberg/czgenepi pull request #978
Opened 2022-03-01 19:09 UTC by edulop91

### Summary:
- **What:** Starting to look into integrating the new happy cli with GitHub actions. As part of this, looking to release a set of common chanzuckerberg/github-actions. Chose the docker step first because it is fairly self-contained and common across many repos. Will follow up with Happy specific actions later
- **Ticket:** NA
- **Env:** `<rdev link>`

### Demos:

### Notes:

### Checklist:
- [ ] I merged latest `<base branch>`
- [ ] I manually verified the change
- [ ] I added labels to my PR
- [ ] I tested in multiple browsers
- [ ] I added relevant unit tests
- [ ] I have notified others of changes they need to make locally (migrations, jobs, package updates, etc)

2022-03-11 17:36 UTC, edulop91 commented
hmm think i'm missing some build keys

2022-03-15 17:55 UTC, jgadling commented on .github/workflows/push-rdev.yml
> +  pull_request:
I think we specifically want to use the `push` event here

2022-03-15 18:16 UTC, jgadling requested changes
This looks good aside from the event hook!

2022-03-16 18:14 UTC, edulop91 commented
see https://github.com/chanzuckerberg/czgenepi/pull/990 instead for the push event instead of pull_request

2022-03-16 18:14 UTC, closed without merging